# Generated by Django 4.2.5 on 2023-09-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.SmallIntegerField()),
                ('distrito', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubigeo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Integrado.ubigeo')),
            ],
        ),
    ]
